### ISSUE TITLE
Create form with multiple input fields to add games

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#1]
### Value statement

As a board game lover 
I want to easily track games played with friends 
so that I can observe my progress over time. 

### Description (text, scribble, wireframe, design)

- It is a form with multiple fields for game name, date, players names, playing time, and simple rating.
- New game (play) entry can be added via a prominent button [Add play]. 

_Structure of the form_
![Bildschirmfoto 2020-07-03 um 15 51 29](https://user-images.githubusercontent.com/61810490/86475645-5d10da00-bd45-11ea-9265-6d10d0fab6c9.png)

_The date picker in action_
![Bildschirmfoto 2020-07-03 um 15 52 32](https://user-images.githubusercontent.com/61810490/86475654-600bca80-bd45-11ea-9bcf-6cba24f9c015.png)

_Detailed information about the play shown after the form_
![Bildschirmfoto 2020-07-03 um 18 23 22](https://user-images.githubusercontent.com/61810490/86489034-4d07f300-bd63-11ea-8997-309d88114534.png)

### Acceptance criteria

- [x] The form reacts on submit (Enter key or button press).
- [x] The fields game name, date and players names are required. 
- [x] The first input has focus at start and after submit.
- [x] The new play is appended to the form. 
- [x] The text is good readable in size and font. 
- [x] The label for the text input field is placed above and aligned with the field.
- [x] The input field for the game name accepts several words separated by a space. The total amount of characters is limited to 100. 
- [x] The date can be selected via a mobile calendar date picker. It includes at least month pagination and the selected date.
- [x] The name field for the players accepts multiple first and last names. Player names are comma-separated. Players can enter more than one first and last name.
- [x] The playing time is given in minutes [Playing time (min)]. Only numerical input. The minimum and maximum values are 0 and 720.
- [x] An input of type range (slider) enables a simple rating with a minimum and maximum value of 1 and 10 and a step value of 1. The selected value is displayed to the right of the slider. 

### Tasks 

- [x] Create feature branch.
- [x] Create AddPlayForm component using Formik and Yup for validation.
- [x] Create Button component.
- [x] Create GameTitleField component.
- [x] Create PlayDateField component.
- [x] Create PlayingTimeField component.
- [x] Create PlayersField component.
- [x] Create PlayRatingField component.
- [x] Write components in Storybook.
- [x] Write component tests.
- [x] Add styles.

### Size

Large
