### ISSUE TITLE
Improve layout and design of detailed information about plays

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#10]
### Value statement 

As a board game player 
I need a scannable and organized overview of my plays 
so that I can fully enjoy the app. 

### Description (text, scribble, wireframe, design)

- The name of the game, date, number of players, and playing time is shown to the right of the game board photo.
- The number of players and playing time are supported with icons for easy and fast access. 

Detailed information of plays nicely organized.
<img width="323" alt="Bildschirmfoto 2020-07-22 um 21 57 10" src="https://user-images.githubusercontent.com/61810490/88222958-0ec96980-cc67-11ea-8eef-6edf788337ee.png">

### Acceptance criteria 

- [x] The icon for the number of players is a group icon.
- [x] The icon for the playing time is a time icon.
- [x] Icons are paired with text labels, which provide a short and meaningful description of the icons purpose.

### Tasks

- [x] Create feature branch.
- [x] Choose icons.
- [x] Add component to Storybook.
- [x] Add component to app.
- [x] Add styling.

### Size 

Small
