### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#12]
### Tasks

**Unit test**

- [ ] Unit functionality

**Component test**

- [ ] Component is rendered
- [ ] Component children are rendered
- [ ] Component tags exist
- [ ] Component functionality 
- [ ] Component hooks 

**Integration test**

- [ ] Communication between DB, API, and components works
