### ISSUE TITLE
Generate unique ID for plays and assign as key

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#13]
### Tasks

- [x] Consult MDN for information about key assignments
- [x] Search for packages that generate uuids
- [x] Install uuid 
- [x] Update updatePlays function to include unique ID
- [x] Assign uuid as key to plays
