### ISSUE TITLE
Change input type for players names

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#2]
### Value statement

As a board game player I want to add each player individually so that I can delete or change the order of players as needed.

### Description (text, scribble, wireframe, design)

- The form shows one input field for a player's name. 
- The icon to add additional players is shown below the input field. 

### Acceptance criteria

- [x] Entering at least one player is mandatory.
- [x] The player has the option to add as many players as needed.
- [x] The button to add players is an icon showing a person.
- [x] Additional players can be deleted via a clear button next to the input. 
- [x] The name of the player should be at least 2 characters.
- [x] The maximum number of characters is 20. 
- [x] Besides alphabetical characters any other characters are allowed. 

### Tasks

- [x] Choose icon. 
- [x] Create button component.
- [x] Update PlayersField component in Storybook.
- [x] Update PlayersField component in app.
- [x] Update Yup validation schema.
- [x] Update mongoose model schema. 
- [x] Add styling.
- [x] Write tests.

### Size

Small
