### ISSUE TITLE
Add image upload functionality

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#3]
### Value statement

As a board game player 
I want to save photos taken during or after plays 
so that I can memorize them better. 

### Description (text, scribble, wireframe, design)

- The user has the possibility to upload one photo. 
- The image upload button is displayed above the input field for the name of the game played. 

_The updated AddPlayForm component including the image upload button_
![Bildschirmfoto 2020-07-03 um 18 21 59](https://user-images.githubusercontent.com/61810490/86486240-0e6e3a80-bd5b-11ea-97e4-d0a9ca7e91cb.png)

_Detailed information about the play shown after the form_
![Bildschirmfoto 2020-07-03 um 18 39 41](https://user-images.githubusercontent.com/61810490/86486814-9a349680-bd5c-11ea-91bc-91825ba07e12.png)

### Acceptance criteria

- [x] The image upload is part of the AddPlayForm component.
- [x] An image is uploaded by clicking on an action button with an image icon.
- [x] Only JPEG files are allowed.
- [x] Image file is stored. 
- [x] The uploaded photo is appended to the form. 

### Tasks

- [x] Create feature branch.
- [x] Create component UploadGameBoardImage in Storybook.
- [x] Update the component AddPlayForm in Storybook.
- [x] Write component tests.
- [x] Add UploadGameBoardImage component to app.
- [x] Update AddPlayForm component in app.
- [x] Add new styles. 
- [x] Server-side POST request for image upload.
- [x] Client-side POST request for image upload.
- [x] Install a middleware to enable file uploads.

### Size

Medium
