### ISSUE TITLE
Show play timeline and play details 

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#4]
### Value statement

As a board game player I want to see details of plays added to my timeline only as needed so that I can quickly scan all my plays. 

### Description (text, scribble, wireframe, design)

- Plays are displayed chronologically and reveal detailed information when clicked.
- Play details include game title, date, name of players, playing time, rating, fractions, scores, and ranking.

_Play timeline_
<img width="366" alt="Bildschirmfoto 2020-07-22 um 21 56 30" src="https://user-images.githubusercontent.com/61810490/88222828-d32e9f80-cc66-11ea-8cfb-788115f7c3f7.png">

_Play details_
<img width="323" alt="Bildschirmfoto 2020-07-22 um 21 57 31" src="https://user-images.githubusercontent.com/61810490/88222844-da55ad80-cc66-11ea-81ee-66c452a5265d.png">

### Acceptance criteria

- [x] Play overview shows a photo of the play, game title, date, and rating.
- [x] When a play is selected, only the detailed information of this play is displayed.
- [x] Play details are closed via an arrow button, which redirects to the play timeline. 
- [x] Information about players, fractions, scores, and ranking are listed below the basic play summary. 
- [x] The text is good readable in size and font.

### Tasks

- [x] Choose appropriate arrow icons.
- [x] Create navigation buttons.
- [x] Add play details components to Storybook.
- [x] Add play details components to app.
- [x] Resize uploaded images. 

### Size

Medium
