### ISSUE TITLE
Add welcome page

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#44]
### Value statement

As a board game player I want a hearty welcome so that I can instantly trust an app about board games.

### Description (text, scribble, wireframe, design)

- An animation makes the user excited about the app.
- The app title is predominant; a subtitle specifies the purpose of the app.
- The app logo above the title of the app helps the user to subtly memorize and identify the app.

### Acceptance criteria

- [ ] The animation should be in decent colors and easy to understand.
- [ ] The title has an unique font.
- [ ] The text must be in a readable font. 
- [ ] A welcome text "Begin your board game journey" navigates the user to the main content.

### Tasks

- [ ] Choose title font.
- [ ] Create animation.
- [ ] Create app logo.
- [ ] Create welcome component.
- [ ] Add welcome component to Storybook.
- [ ] Add welcome component to app.
- [ ] Write unit tests.

### Size

Small
