### ISSUE TITLE
Add game page

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#49]
### Value statement

As a board game player I want an overview / list of existing games from which I can choose games I have already played and I want to play in the future. 

### Description (text, scribble, wireframe, design)

- Games with information from the BGG website are placed as tiles in two columns. 
- A photo of the board game cover is placed above the game title.
- Enough space around the games ensures readability.  

### Acceptance criteria

- [x] The title of the game should not be too long. Maximum two lines are shown, the rest is hidden.
- [x] Information about the number of players is placed above the title.
- [x] The title of the page is "Games".
- [x] Images are presented in neumorphism style.
- [x] The text must be in a readable font. 
- [x] Filter categories "all games", "played", and "wishlist" are placed above the games list.
- [x] Selected filter category is sufficiently highlighted. 

### Tasks

- [x] Research "mock" games on BGG.
- [x] Create gameData in json format.
- [x] Create Game, GameCollection, and Games component.
- [ ] Add components to Storybook.
- [x] Add components to app.
- [x] Add styling.

### Size

Small
