### ISSUE TITLE
Add edit button to edit play entries

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#5]
### Value statement

As a board game player I want the possibility to edit and add information to my plays. 

### Description (text, scribble, wireframe, design)

- Plays can be edited on the page about play details.
- The edit button is placed in an easily accessible position. 
- The user can confirm the action via a "cancel" or "save" button. 

### Acceptance criteria

- [ ] The edit button is placed on the top of the page and shows a simple edit icon.
- [ ] The edit button disappears when clicked. 
- [ ] Editable content transforms to an input field for inline editing. 
- [ ] The input fields are of the same style as the fields of the AddPlayForm component. 
- [ ] When editing is activated two buttons pop-up, a "cancel" and a "save" button.
- [ ] The cancel button aborts changes and the content is set to the original state.
- [ ] Content edited is saved to localStorage / the database when the "save" button is clicked. 
- [ ] The same field Yup validation schema as for the AddPlayForm fields apply. 

### Tasks

- [x] Create edit button.
- [x] Add edit component.
- [x] Create cancel button.
- [x] Create save button.
- [x] Update PlayRanking component.
- [x] Update PlayOverviewPage component.
- [ ] Update PlayDetails component. 
- [ ] Update playsLocalStorageClient.
- [ ] Update playsRestClient.
- [ ] Add validation schema.
- [ ] Add components to Storybook.

### Size

Large
