### ISSUE TITLE
Add filter

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#50]
### Value statement

As a board game player I want to organize and filter games, which I have already played and which I want to play in the future.  

### Description (text, scribble, wireframe, design)

- The filter categories are placed below the heading of the Games page.
- Games can be categorized in all games, games already played, and games on wish list. 
- The active filter is highlighted. 

### Acceptance criteria

- [x] Filter categories are "All Games", "Played", and "Wishlist".
- [x] Easy integrated filter; categories are sublinks of the Games page.
- [x] The Games navigation button is highlighted when any category is active.
- [x] The filter is highlighted in a different color than the text color (primary color) and underlined.
- [x] Games can be added to the "Played" category by clicking on a finish icon.
- [x] Games can be added to the "Wishlist" category by clicking on a heart icon.
- [x] Games can be removed from "Played" and "Wishlist" via a click on the respective icon. 

### Tasks

- [x] Select icons.
- [x] Write toggle function for "Played" and "Wishlist".
- [x] Setup user client.
- [x] Setup games client. 
- [x] Update GameDetails component.
 
### Size

Small
