### ISSUE TITLE
Add game details page

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#51]
### Value statement

As a board game player I want a detailed overview of interesting games on the market so that I can better choose games and plan board game sessions. 

### Description (text, scribble, wireframe, design)

- An image of the board game cover introduces the game. 
- Title and publishing date are the main headings. 
- Players, age, and playing time displayed next to each other as on board game boxes.
- Each play comes with a description as well as key features such as type, categories, and mechanisms. 
- The average BGG rating is displayed as a star next to the game cover. 

### Acceptance criteria

- [x] Essential game information is displayed in the same manner as essential play information.
- [x] The description is left-aligned and divided into paragraphs for a better user experience. 
- [x] The board game cover is shown in full size. 
- [x] A back button leads back to the Games page. 
- [x] When the details page is active the navigation buttons are inactive. 
- [x] Key features (type, category, and mechanism) are button-shaped (high emphasis button style) so that they can be transformed to tags in a future approach. 

### Tasks

- [x] Create GameDetails component.
- [x] Add GameDetails component to app.
- [x] Create GameOverviewPage component.
- [x] Add GameOverviewPage component to app.
- [x] Add components to Storybook.

### Size

Small
