### ISSUE TITLE
Add navigation

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#52]
### Value statement

As a board game player I need to easily navigate around the app so that I can quickly access relevant information. 

### Description (text, scribble, wireframe, design)

- The navigation comprises two buttons, one for plays and one for games.
- Icons are supported by titles. 
- Navigation buttons have space between. 

### Acceptance criteria

- [x] A list icon guides to the Plays page.
- [x] A app icon guides to the Games page.
- [x] The active link is shown in a different color.
- [x] In addition, the active link is visually highlighted in neumorphism style.
- [x] The titles are easily recognizable.  

### Tasks

- [x] Add navigation component to app.
- [ ] Add navigation component to Storybook.
- [x] Add routes to App.js

### Size

Small
