### ISSUE TITLE
Add plus button to add play entries

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#6]
### Value statement

As a board game player I want to press a nice plus button to add plays to my timeline so that the add play form is hidden when I do not need it.

### Description (text, scribble, wireframe, design)

- The plus button is placed in the right lower corner of the play timeline, which shows an overview of played games. 
- The plus button reveals the add play form when clicked. 

_Plus button on play timeline_
<img width="322" alt="Bildschirmfoto 2020-07-13 um 20 45 25" src="https://user-images.githubusercontent.com/61810490/87341493-02982a80-c54a-11ea-9829-afb6d5492b59.png">

### Acceptance criteria

- [x] The form is hidden by default.
- [x] When the plus button is clicked, the form appears on the whole screen. 
- [x] The form disappears when successfully submitted.

### Tasks

- [x] Choose appropriate plus icon.
- [x] Add button to play timeline (page).
- [x] Add component to Storybook.
- [x] Implement behavior to show the form only when plus button was pressed.
- [x] Implement behavior to hide form when submitted. 

### Size

Small
