### ISSUE TITLE
Create customized rating component

### ISSUE THREAD

**Issue by Fractalbonita** [Fractalbonita/capstone-project#7]
### Value statement

As a board game player I want to easily rate my last play according to the BGG rating system so that I can compare different plays. 

### Description (text, scribble, wireframe, design)

- Plays are rated by clicking on the respective amount of rating icons.
- The rating system ranges from 1 to 10.

### Acceptance criteria

- [x] The new customized rating component substitutes the slider. 
- [x] Each rating value is represented by a rating icon.
- [x] The rating icon can be of any suitable shape and theme. 
- [x] The rating is displayed as number in the play overview and details. 

### Tasks

- [x] Add rating component to Storybook.
- [x] Add rating component to app. 
- [x] Display rating in play overview and details. 
- [x] Update AddPlayForm component in Storybook.
- [x] Update AddPlayForm component in app.
- [x] Add styles

### Size

Small
